//
// Created by eec on 18/06/25.
//

#ifndef ENUMMENU_H
#define ENUMMENU_H

enum ENUM_MENU_PRINCIPAL {
    EXIBIR_MENU_LOCAL = '1',
    EXIBIR_MENU_VEICULO = '2',
    EXIBIR_MENU_PEDIDO = '3',
    EXIBIR_MENU_ROTA = '4',
    EXIBIR_MENU_BANCO = '5',
    FINALIZAR_PROGRAMA = '6'
};

enum ENUM_MENU_LOCAL {
    CRIAR_LOCAL = '1',
    EXCLUIR_LOCAL = '2',
    LISTAR_TODOS_LOCAIS = '3',
    VOLTAR_PARA_O_MENU_PRINCIPAL_LOCAL = '4',
};

enum ENUM_MENU_VEICULO {
    CRIAR_VEICULO = '1',
    EXCLUIR_VEICULO = '2',
    LISTAR_TODOS_VEICULOS = '3',
    ATUALIZAR_VEICULOS = '4',
    VOLTAR_PARA_O_MENU_PRINCIPAL_VEICULO = '5'
};

enum ENUM_MENU_PEDIDO {
    CRIAR_PEDIDO = '1',
    EXCLUIR_PEDIDO = '2',
    LISTAR_TODOS_PEDIDOS = '3',
    VOLTAR_PARA_O_MENU_PRINCIPAL_PEDIDOS = '4',
};

enum ENUM_MENU_ROTAS {

};

enum ENUM_MENU_BANCO {
    SALVAR_TODOS_DADOS = '1',
    RESTAURAR_DADOS_DE_BACKUPS_ANTIGOS = '2',
    VOLTAR_PARA_O_MENU_PRINCIPAL_BANCO = '3',
};

#endif //ENUMMENU_H
